spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-security
            client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a
        provider:
          keycloak:
            issuer-uri: https://keycloak-spring-security-cf.cfapps.io/auth/realms/demo